### ISSUE TITLE
Ide cannot be started

### ISSUE THREAD

**Issue by cenkce** [che-samples/che-plugin-json#8]
I build and run this plugin as an IDE in my localhost but it can't run. Although docker successfully started IDE.

**Comment by cenkce** [comment]
```
2018-05-24 16:37:48,483[ost-startStop-1]  [ERROR] [o.a.c.c.C.[.[localhost].[/] 4671]    - Error configuring application listener of class [org.eclipse.che.inject.CheBootstrap]
java.lang.ClassNotFoundException: org.eclipse.che.inject.CheBootstrap
	at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1291)
	at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1119)
	at org.apache.catalina.core.DefaultInstanceManager.loadClass(DefaultInstanceManager.java:512)
	at org.apache.catalina.core.DefaultInstanceManager.loadClassMaybePrivileged(DefaultInstanceManager.java:493)
	at org.apache.catalina.core.DefaultInstanceManager.newInstance(DefaultInstanceManager.java:119)
	at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:4667)
	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5207)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
	at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:752)
	at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:728)
	at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:734)
	at org.apache.catalina.startup.HostConfig.deployWAR(HostConfig.java:988)
	at org.apache.catalina.startup.HostConfig$DeployWar.run(HostConfig.java:1860)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)
2018-05-24 16:37:48,488[ost-startStop-1]  [ERROR] [o.a.c.c.C.[.[localhost].[/] 4677]    - Skipped installing application listeners due to previous error(s)
2018-05-24 16:37:48,494[ost-startStop-1]  [ERROR] [o.a.c.core.StandardContext 5208]     - One or more listeners failed to start. Full details will be found in the appropriate container log file
2018-05-24 16:37:48,498[ost-startStop-1]  [ERROR] [o.a.c.core.StandardContext 5259]     - Context [] startup failed due to previous errors
2018-05-24 16:37:48,529[ost-startStop-1]  [INFO ] [o.a.c.startup.HostConfig 1023]       - Deployment of web application archive [/assembly/tomcat/webapps/ROOT.war] has finished in [2,378] ms
2018-05-24 16:37:48,538[ost-startStop-1]  [INFO ] [o.a.c.startup.HostConfig 959]        - Deploying web application archive [/assembly/tomcat/webapps/dashboard.war]
2018-05-24 16:37:53,329[ost-startStop-1]  [INFO ] [o.a.c.startup.HostConfig 1023]       - Deployment of web application archive [/assembly/tomcat/webapps/dashboard.war] has finished in [4,791] ms
2018-05-24 16:37:53,336[ost-startStop-1]  [INFO ] [o.a.c.startup.HostConfig 959]        - Deploying web application archive [/assembly/tomcat/webapps/workspace-loader.war]
2018-05-24 16:37:54,286[ost-startStop-1]  [INFO ] [o.a.c.startup.HostConfig 1023]       - Deployment of web application archive [/assembly/tomcat/webapps/workspace-loader.war] has finished in [950] ms
2018-05-24 16:37:54,307[main]             [INFO ] [o.a.c.http11.Http11NioProtocol 632]  - Starting ProtocolHandler ["http-nio-8080"]
2018-05-24 16:37:54,339[main]             [INFO ] [o.a.catalina.startup.Catalina 683]   - Server startup in 46564 ms
2018-05-24 16:40:59,800[nio-8080-exec-6]  [INFO ] [o.e.c.a.w.s.WorkspaceManager 459]    - Workspace 'che/wksp-04rv' with id 'workspace6l8uzfbec92ourzv' created by user 'che'
```
